### ISSUE TITLE
Please add Dragonflight spell visuals to photo mode

### ISSUE THREAD

**Issue by LakeQueen** [Peterodox/Narcissus#20]
We're currently missing all the evoker precast animations (ruby flames, dream mists, spellfrost, volcanic, bronze sands) and also the body effects. Would really like to have them in photo mode if at all possible. <3

Alternatively, can you please add a guide on how we can get their ids to use in the Custom Visual field?

**Comment by Peterodox** [comment]
Hi!
I've added a ❔ button next to the visual ID input box, telling you how to find the ID if you know the spell name.
Sorry, it's unlikely I'll update the existing list. It simply took so much time because I'll have to test them one by one in-game to see if they display correctly, name them, and take screenshots for previews.

**Comment by Peterodox** [comment]
Hi!
I've added a ❔ button next to the visual ID input box, telling you how to find the ID if you know the spell name.
Sorry, it's unlikely I'll update the existing list. It simply took so much time because I'll have to test them one by one in-game to see if they display correctly, name them, and take screenshots for previews.
